---
galaxy_info:
  author: lisandius
  description: Install nginx and configure virtual hosts from a list of sites
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - noble
  galaxy_tags: [nginx, web]
dependencies: []
